darcy_crkp_2f – ParaGEMS
darcy_crkp_2f Program
Pieter Boom
2019/08/23
63 statements
Source File
Uses
common_mod
mpi_mod
partition_mod
darcy_mod
solver_mod
Miniapp to solve two-field Darcy flow in parallel using PETSc KSP with cracking
Calls
Contents
Variables
fname msg crck_id exit_cond
Variables
Type Attributes Name Initial
character(len=slen) :: fname
character(len=slen) :: msg
integer :: crck_id
logical :: exit_cond
Call graph
darcy_crkp_2f~2: calls end_mpi:, extract_sol_ksp:, open_unsteady_log:, write_centers_matlab2:, rootwrite_log:, initialise_geo:, solve_ksp:, start_mpi:, write_solution_matlab2:, clean_up:, end_petsc:, parallel_setup:, get_rhs_darcy:, calc_whitney_c2_bc:, identify_crack:, read_input_darcy:, finalise_darcy:, initialise_darcy:, write_pressure_matlab2:, write_prml_volumes_matlab2:, syncwrite_log:, start_petsc:, get_lhs_darcy:, write_unsteady_d0s:, close_unsteady_log:, identify_crack3:
end_mpi: calls syncwrite_log:, syncwrite_log_time:, mpi_finalize:, close_log:
extract_sol_ksp: calls syncwrite_log_time:, num_elm:, isdestroy:, vecscatterend:, lcl_complex:, vecscatterdestroy:, vecscattercreate:, glb_num_elm:, vecscatterbegin:, vecdestroy:
open_unsteady_log: calls mpi_bcast:
solve_ksp: calls syncwrite_log:, kspgetresidualnorm:, kspcreate:, kspsetup:, kspview:, pcfactorsetmatorderingtype:, kspsettype:, kspsolve:, pcsettype:, kspmonitorset:, kspsetoperators:, petscviewerandformatcreate:, kspsettolerances:, mpi_wtime:, kspsetfromoptions:, kspgetpc:, kspgetiterationnumber:
start_mpi: calls end_mpi:, syncwrite_log_mpidata:, mpi_barrier:, open_log:, mpi_comm_rank:, mpi_wtime:, mpi_comm_size:, mpi_init:
end_petsc: calls petscfinalize:
parallel_setup: calls syncwrite_log:, syncwrite_log_time:, exchange_prml_nodes:, get_glb_indx_dual_vlm:, read_prml_elms2:, partition_dual:, read_nodes_prml:, get_connectivity:, calc_bndry_cobndry:, get_glb_indx:
get_rhs_darcy: calls syncwrite_log:, bc_press:, syncwrite_log_time:, num_elm:, vecassemblyend:, lcl_complex:, mpi_wtime:, glb_num_elm:, vecassemblybegin:, read_bndry_cond2:, mpi_reduce:
identify_crack: calls syncwrite_log:, syncwrite_log_time:, num_elm:, mpi_allreduce:, vecassemblyend:, lcl_complex:, mpi_wtime:, vecassemblybegin:
read_input_darcy: calls end_mpi:, rootwrite_log:, syncwrite_log:, check_param_darcy:
finalise_darcy: calls matdestroy:, vecdestroy:, kspdestroy:
initialise_darcy: calls syncwrite_log:, matcreate:, syncwrite_log_time:, vecgetvalues:, num_elm:, vecassemblyend:, veccreatempi:, vecsetfromoptions:, lcl_complex:, mpi_wtime:, glb_num_elm:, matsetsizes:, vecduplicate:, vecdestroy:, vecassemblybegin:, vecgetownershiprange:, matsetfromoptions:
syncwrite_log: calls mpi_barrier:
start_petsc: calls end_mpi:, syncwrite_log:, petscinitialize:
get_lhs_darcy: calls syncwrite_log:, syncwrite_log_time:, matsetoption:, num_elm:, matassemblybegin:, lcl_complex:, mpi_wtime:, matassemblyend:, glb_num_elm:
identify_crack3: calls syncwrite_log:, syncwrite_log_time:, num_elm:, vecassemblyend:, lcl_complex:, mpi_wtime:, vecassemblybegin:, matzerorowscolumns:, mpi_reduce:
syncwrite_log_mpidata: calls mpi_barrier:
syncwrite_log_time: calls rootwrite_log:, mpi_barrier:, mpi_wtime:
exchange_prml_nodes: calls mpi_barrier:, lcl_complex:, mpi_waitall:, mpi_request_free:, num_send:, adj_proc:, num_recv:
get_glb_indx_dual_vlm: calls num_elm:, lcl_complex:
open_log: calls mpi_bcast:
read_prml_elms2: calls mpi_barrier:, num_elm:, mpi_bcast:, lcl_complex:, glb_num_elm:, elm2proc:, indx_offset:, root_open_file_read:, num_pelm_pp:
partition_dual: calls num_elm:, mpi_bcast:, lcl_complex:, glb_num_elm:, indx_offset:, num_pelm_pp:
read_nodes_prml: calls num_elm:, mpi_bcast:, lcl_complex:, glb_num_elm:, mpi_recv:, indx_offset:, root_open_file_read:, idnint:, num_pelm_pp:, mpi_send:
get_connectivity: calls rootwrite_log:, mpi_barrier:, num_elm:, lcl_complex:, mpi_waitall:, mpi_request_free:, num_send:, adj_proc:, index_in_list:, num_recv:
calc_bndry_cobndry: calls syncwrite_log:, syncwrite_log_time:, num_elm:, count_bndry_cobndry:, allocate_bndry_cobndry:, build_bndry_work_array:, set_bndry_cobndry:
get_glb_indx: calls num_elm:, lcl_complex:, read_glb_indx2:, exchange_glb_indx:
check_param_darcy: calls rootwrite_log:
read_bndry_cond2: calls mpi_barrier:, num_elm:, mpi_bcast:, lcl_complex:, glb_num_elm:, root_open_file_read:
count_bndry_cobndry: calls num_elm:, lcl_complex:, any_element_in_list:
elm2proc: calls num_pelm_pp:
root_open_file_read: calls mpi_bcast:
allocate_bndry_cobndry: calls num_elm:, lcl_complex:
read_glb_indx2: calls end_mpi:, mpi_barrier:, num_elm:, mpi_bcast:, lcl_complex:, glb_num_elm:, elm2proc:, indx_offset:, root_open_file_read:
build_bndry_work_array: calls num_elm:, lcl_complex:
set_bndry_cobndry: calls num_elm:, lcl_complex:, elm2proc:
exchange_glb_indx: calls mpi_barrier:, lcl_complex:, mpi_waitall:, mpi_request_free:, num_send:, adj_proc:, num_recv: