darcy_crkp_1f – ParaGEMS
darcy_crkp_1f Program
Pieter Boom
2019/08/23
27 statements
Source File
Uses
common_mod
mpi_mod
partition_mod
darcy_mod
solver_mod
Miniapp to solve one-field Darcy flow in parallel using PETSc KSP with cracking
Calls
Contents
None
Call graph
darcy_crkp_1f: calls end_mpi:, syncwrite_log:, rootwrite_log:, start_mpi:, start_petsc:, get_rhs_darcy:, get_lhs_darcy:, calc_whitney_c2_bc:, parallel_setup:, read_input_darcy:, finalise_darcy:, clean_up:, initialise_darcy:, solve_ksp:, end_petsc:, initialise_geo:, write_solution_d0s:
end_mpi: calls syncwrite_log:, syncwrite_log_time:, mpi_finalize:, close_log:
syncwrite_log: calls mpi_barrier:
start_mpi: calls end_mpi:, syncwrite_log_mpidata:, mpi_barrier:, mpi_wtime:, mpi_comm_size:, open_log:, mpi_init:, mpi_comm_rank:
start_petsc: calls end_mpi:, syncwrite_log:, petscinitialize:
get_rhs_darcy: calls syncwrite_log:, bc_press:, syncwrite_log_time:, num_elm:, read_bndry_cond2:, vecassemblyend:, lcl_complex:, mpi_wtime:, glb_num_elm:, mpi_reduce:, vecassemblybegin:
get_lhs_darcy: calls syncwrite_log:, syncwrite_log_time:, matsetoption:, num_elm:, matassemblybegin:, lcl_complex:, mpi_wtime:, matassemblyend:, glb_num_elm:
parallel_setup: calls syncwrite_log:, syncwrite_log_time:, exchange_prml_nodes:, get_glb_indx_dual_vlm:, read_prml_elms2:, partition_dual:, read_nodes_prml:, get_connectivity:, calc_bndry_cobndry:, get_glb_indx:
read_input_darcy: calls end_mpi:, syncwrite_log:, rootwrite_log:, check_param_darcy:
finalise_darcy: calls vecdestroy:, matdestroy:, kspdestroy:
initialise_darcy: calls syncwrite_log:, matsetsizes:, syncwrite_log_time:, vecgetvalues:, vecdestroy:, num_elm:, matcreate:, vecassemblyend:, veccreatempi:, vecsetfromoptions:, lcl_complex:, matsetfromoptions:, mpi_wtime:, glb_num_elm:, vecgetownershiprange:, vecduplicate:, vecassemblybegin:
solve_ksp: calls syncwrite_log:, kspgetresidualnorm:, kspsolve:, kspcreate:, kspsetup:, pcfactorsetmatorderingtype:, pcsettype:, kspmonitorset:, kspview:, petscviewerandformatcreate:, kspsettolerances:, kspsetoperators:, mpi_wtime:, kspsetfromoptions:, kspsettype:, kspgetiterationnumber:, kspgetpc:
end_petsc: calls petscfinalize:
syncwrite_log_mpidata: calls mpi_barrier:
syncwrite_log_time: calls rootwrite_log:, mpi_barrier:, mpi_wtime:
exchange_prml_nodes: calls mpi_barrier:, lcl_complex:, mpi_waitall:, mpi_request_free:, num_send:, adj_proc:, num_recv:
get_glb_indx_dual_vlm: calls num_elm:, lcl_complex:
read_prml_elms2: calls mpi_barrier:, num_elm:, lcl_complex:, glb_num_elm:, elm2proc:, indx_offset:, root_open_file_read:, mpi_bcast:, num_pelm_pp:
partition_dual: calls num_elm:, lcl_complex:, glb_num_elm:, indx_offset:, mpi_bcast:, num_pelm_pp:
read_nodes_prml: calls num_elm:, lcl_complex:, glb_num_elm:, mpi_recv:, indx_offset:, root_open_file_read:, mpi_bcast:, idnint:, num_pelm_pp:, mpi_send:
read_bndry_cond2: calls mpi_barrier:, num_elm:, lcl_complex:, glb_num_elm:, root_open_file_read:, mpi_bcast:
get_connectivity: calls rootwrite_log:, mpi_barrier:, num_elm:, lcl_complex:, mpi_waitall:, mpi_request_free:, num_send:, adj_proc:, index_in_list:, num_recv:
calc_bndry_cobndry: calls syncwrite_log:, syncwrite_log_time:, num_elm:, count_bndry_cobndry:, allocate_bndry_cobndry:, build_bndry_work_array:, set_bndry_cobndry:
get_glb_indx: calls num_elm:, lcl_complex:, read_glb_indx2:, exchange_glb_indx:
open_log: calls mpi_bcast:
check_param_darcy: calls rootwrite_log:
count_bndry_cobndry: calls num_elm:, lcl_complex:, any_element_in_list:
elm2proc: calls num_pelm_pp:
root_open_file_read: calls mpi_bcast:
read_glb_indx2: calls end_mpi:, mpi_barrier:, num_elm:, lcl_complex:, glb_num_elm:, elm2proc:, indx_offset:, root_open_file_read:, mpi_bcast:
allocate_bndry_cobndry: calls num_elm:, lcl_complex:
build_bndry_work_array: calls num_elm:, lcl_complex:
set_bndry_cobndry: calls num_elm:, lcl_complex:, elm2proc:
exchange_glb_indx: calls mpi_barrier:, lcl_complex:, mpi_waitall:, mpi_request_free:, num_send:, adj_proc:, num_recv: