darcy_crkp_2f – ParaGEMS
darcy_crkp_2f Program
Pieter Boom
2019/08/23
69 statements
Source File
Uses
common_mod
mpi_mod
partition_mod
darcy_mod
solver_mod
Miniapp to solve two-field Darcy flow in parallel using PETSc KSP with cracking
Calls
Contents
Variables
fname msg crck_id i exit_cond
Variables
Type Attributes Name Initial
character(len=slen) :: fname
character(len=slen) :: msg
integer :: crck_id
integer :: i
logical :: exit_cond
Call graph
darcy_crkp_2f: calls end_mpi:, open_unsteady_log:, write_unsteady_d0s2:, rootwrite_log:, initialise_geo:, start_mpi:, write_pressure_matlab:, initialise_darcy2:, write_centers_matlab:, get_rhs_darcy2:, clean_up:, solve_ksp2:, end_petsc:, parallel_setup:, get_lhs_darcy2:, calc_whitney_c2_bc:, read_input_darcy:, finalise_darcy:, write_solution_matlab:, extract_sol_ksp2:, syncwrite_log:, start_petsc:, identify_crack5:, identify_crack7:, identify_crack6:, close_unsteady_log:, identify_crack4:, write_prml_volumes_matlab:
end_mpi: calls syncwrite_log:, syncwrite_log_time:, mpi_finalize:, close_log:
open_unsteady_log: calls mpi_bcast:
start_mpi: calls end_mpi:, syncwrite_log_mpidata:, mpi_barrier:, mpi_comm_rank:, mpi_wtime:, mpi_comm_size:, open_log:, mpi_init:
initialise_darcy2: calls syncwrite_log:, syncwrite_log_time:, num_elm:, lcl_complex:, mpi_wtime:
get_rhs_darcy2: calls syncwrite_log:, bc_press:, syncwrite_log_time:, num_elm:, matcreatenest:, read_bndry_cond2:, lcl_complex:, matgetownershiprange:, vecsetfromoptions:, vecassemblyend:, mpi_wtime:, glb_num_elm:, asub:, vecdestroy:, vecduplicate:, isg:, vecassemblybegin:
solve_ksp2: calls syncwrite_log:, kspgetconvergedreason:, kspsolve:, kspcreate:, kspsetup:, kspview:, sub2pc_id:, sub2ksp_id:, kspgetpc:, subksp_id:, kspgetresidualnorm:, pcsettype:, subpc_id:, kspmonitorset:, petscviewerandformatcreate:, kspsettolerances:, kspsetoperators:, pcsetup:, mpi_wtime:, kspsetfromoptions:, kspsettype:, pcfieldsplitsetschurfacttype:, kspgetiterationnumber:, pcfieldsplitsetschurpre:, pcfieldsplitgetsubksp:, pcfieldsplitsettype:, isg:, kspdestroy:
end_petsc: calls petscfinalize:
parallel_setup: calls syncwrite_log:, syncwrite_log_time:, exchange_prml_nodes:, get_glb_indx_dual_vlm:, read_prml_elms2:, partition_dual:, read_nodes_prml:, get_connectivity:, calc_bndry_cobndry:, get_glb_indx:
get_lhs_darcy2: calls syncwrite_log:, syncwrite_log_time:, num_elm:, matcreatenest:, lcl_complex:, matnestgetiss:, mpi_wtime:, glb_num_elm:, matsetoption:, asub:
read_input_darcy: calls end_mpi:, rootwrite_log:, syncwrite_log:, check_param_darcy:
finalise_darcy: calls matdestroy:, vecdestroy:, kspdestroy:
extract_sol_ksp2: calls syncwrite_log_time:, num_elm:, isdestroy:, vecscatterbegin:, vecscattercreate:, lcl_complex:, vecscatterend:, vecscatterdestroy:, vecdestroy:, isg:
syncwrite_log: calls mpi_barrier:
start_petsc: calls end_mpi:, syncwrite_log:, petscinitialize:
identify_crack5: calls syncwrite_log:, syncwrite_log_time:, num_elm:, lcl_complex:, vecassemblyend:, mpi_wtime:, asub:, mpi_reduce:, vecassemblybegin:
identify_crack7: calls syncwrite_log:, syncwrite_log_time:, num_elm:, lcl_complex:, vecassemblyend:, mpi_wtime:, asub:, mpi_reduce:, vecassemblybegin:
identify_crack6: calls syncwrite_log:, syncwrite_log_time:, num_elm:, mpi_allreduce:, lcl_complex:, mpi_bcast:, vecassemblyend:, mpi_wtime:, glb_num_elm:, vecsetvalues:, asub:, mpi_reduce:, vecassemblybegin:
identify_crack4: calls syncwrite_log:, syncwrite_log_time:, num_elm:, mpi_allreduce:, lcl_complex:, vecassemblyend:, mpi_wtime:, asub:, vecassemblybegin:
syncwrite_log_mpidata: calls mpi_barrier:
syncwrite_log_time: calls rootwrite_log:, mpi_barrier:, mpi_wtime:
exchange_prml_nodes: calls mpi_barrier:, lcl_complex:, mpi_waitall:, mpi_request_free:, num_send:, adj_proc:, num_recv:
get_glb_indx_dual_vlm: calls num_elm:, lcl_complex:
check_param_darcy: calls rootwrite_log:
read_prml_elms2: calls mpi_barrier:, num_elm:, lcl_complex:, mpi_bcast:, glb_num_elm:, elm2proc:, indx_offset:, root_open_file_read:, num_pelm_pp:
partition_dual: calls num_elm:, lcl_complex:, mpi_bcast:, glb_num_elm:, indx_offset:, num_pelm_pp:
read_nodes_prml: calls num_elm:, lcl_complex:, mpi_bcast:, glb_num_elm:, mpi_recv:, indx_offset:, root_open_file_read:, idnint:, num_pelm_pp:, mpi_send:
read_bndry_cond2: calls mpi_barrier:, num_elm:, lcl_complex:, mpi_bcast:, glb_num_elm:, root_open_file_read:
get_connectivity: calls rootwrite_log:, mpi_barrier:, num_elm:, lcl_complex:, mpi_waitall:, mpi_request_free:, num_send:, adj_proc:, index_in_list:, num_recv:
calc_bndry_cobndry: calls syncwrite_log:, syncwrite_log_time:, num_elm:, count_bndry_cobndry:, allocate_bndry_cobndry:, build_bndry_work_array:, set_bndry_cobndry:
get_glb_indx: calls num_elm:, lcl_complex:, read_glb_indx2:, exchange_glb_indx:
open_log: calls mpi_bcast:
count_bndry_cobndry: calls num_elm:, lcl_complex:, any_element_in_list:
elm2proc: calls num_pelm_pp:
root_open_file_read: calls mpi_bcast:
allocate_bndry_cobndry: calls num_elm:, lcl_complex:
read_glb_indx2: calls end_mpi:, mpi_barrier:, num_elm:, lcl_complex:, mpi_bcast:, glb_num_elm:, elm2proc:, indx_offset:, root_open_file_read:
build_bndry_work_array: calls num_elm:, lcl_complex:
set_bndry_cobndry: calls num_elm:, lcl_complex:, elm2proc:
exchange_glb_indx: calls mpi_barrier:, lcl_complex:, mpi_waitall:, mpi_request_free:, num_send:, adj_proc:, num_recv: