allocate_bndry_cobndry – ParaGEMS
allocate_bndry_cobndry Subroutine
Pieter Boom
2019/08/23
28 statements
Source File
public subroutine allocate_bndry_cobndry(k, cnt, bndry_cnt, cobndry_cnt, ext_cnt, surf_cnt)
Allocate [co-]boundaries structures/variables
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: k
simplicial order
integer, intent(in) :: cnt
counter (k-1) element
integer, intent(in) :: bndry_cnt(:)
temp # local boundaries
integer, intent(in) :: cobndry_cnt(:)
temp # co-boundaries
integer, intent(in) :: ext_cnt(2)
counter external boundaries
integer, intent(in) :: surf_cnt
counter surface boundaries
Calls
Called by
Contents
Variables
i
Variables
Type Visibility Attributes Name Initial
integer, public :: i
counter
Call graph
allocate_bndry_cobndry: calls lcl_complex:, num_elm:
calc_bndry_cobndry: calls allocate_bndry_cobndry:
parallel_setup: calls calc_bndry_cobndry:
darcy_1f: calls parallel_setup:
darcy_crkp_2f: calls parallel_setup:
darcy: calls parallel_setup:
darcy_crkp_1f: calls parallel_setup:
darcy_crkp_2f~2: calls parallel_setup:
darcy_2f: calls parallel_setup: