calc_circumcenters – ParaGEMS
calc_circumcenters Subroutine
Pieter Boom
2019/08/23
27 statements
Source File
public subroutine calc_circumcenters(k)
Compute circumcenter of given elements
Arguments
Type Intent Optional Attributes Name
integer :: k
simplicial order
Calls
Called by
Contents
Variables
i j kp A b ipiv pts work
Variables
Type Visibility Attributes Name Initial
integer, public :: i
loop indices
integer, public :: j
loop indices
integer, public :: kp
simplicial order plus one
real(kind=iwp), public, ALLOCATABLE :: A(:,:)
solution variables
real(kind=iwp), public, ALLOCATABLE :: b(:)
solution variables
real(kind=iwp), public, ALLOCATABLE :: ipiv(:)
work arrays
real(kind=iwp), public, ALLOCATABLE :: pts(:,:)
bounding points
real(kind=iwp), public, ALLOCATABLE :: work(:)
work arrays
Call graph
calc_circumcenters: calls lcl_complex:, num_elm:, dsysv:
initialise_geo: calls calc_circumcenters: