calc_dual_dir – ParaGEMS
calc_dual_dir Subroutine
Pieter Boom
2019/08/23
19 statements
Source File
public subroutine calc_dual_dir()
Compute the unit direction of dual edges
Arguments
None
Calls
Called by
Contents
Variables
i j
Variables
Type Visibility Attributes Name Initial
integer, public :: i
loop counters
integer, public :: j
loop counters
Call graph
calc_dual_dir: calls lcl_complex:, exchange_dual_dir:, num_elm:
exchange_dual_dir: calls lcl_complex:, mpi_waitall:, mpi_request_free:, mpi_barrier:, num_send:, adj_proc:, num_recv:
initialise_geo: calls calc_dual_dir: