calc_dual_vlm – ParaGEMS
calc_dual_vlm Subroutine
Pieter Boom
2019/08/23
25 statements
Source File
public subroutine calc_dual_vlm()
Compute volume for dual elements of all geometric order
Arguments
None
Calls
Called by
Contents
Variables
i indx k pts sgn
Variables
Type Visibility Attributes Name Initial
integer, public :: i
loop counters
integer, public :: indx
loop counters
integer, public :: k
simplicial order
real(kind=iwp), public, ALLOCATABLE :: pts(:,:)
bounding points
real(kind=iwp), public, ALLOCATABLE :: sgn(:)
sign of volume elements
Call graph
calc_dual_vlm: calls lcl_complex:, calc_dual_vlm_i:, num_elm:, add_points_i:
calc_dual_vlm_i: calls lcl_complex:, calc_unsgnd_vlm:
add_points_i: calls lcl_complex:
calc_unsgnd_vlm: calls determinant:
determinant: calls determinant:
initialise_geo: calls calc_dual_vlm: