calc_prml_dir – ParaGEMS
calc_prml_dir Subroutine
Pieter Boom
2019/08/23
10 statements
Source File
public subroutine calc_prml_dir()
Compute the unit direction of primal edges
Arguments
None
Calls
Called by
Contents
Variables
i
Variables
Type Visibility Attributes Name Initial
integer, public :: i
loop counter
Call graph
calc_prml_dir: calls lcl_complex:, num_elm:
initialise_geo: calls calc_prml_dir: