calc_bndry_cobndry – ParaGEMS
calc_bndry_cobndry Subroutine
Pieter Boom
2019/08/20
38 statements
Source File
public subroutine calc_bndry_cobndry()
Recursively compute element (co-)boundaries from highest to lowest geometric order
Arguments
None
Calls
Called by
Contents
Variables
bndry bndry_cnt cnt cobndry_cnt ext_cnt k surf_cnt work lwork
Variables
Type Visibility Attributes Name Initial
integer, public, ALLOCATABLE :: bndry(:,:)
temp. boundary work array
integer, public, ALLOCATABLE :: bndry_cnt(:)
counter local boundaries
integer, public :: cnt
counter boundaries
integer, public, ALLOCATABLE :: cobndry_cnt(:)
counter co-boundaries
integer, public :: ext_cnt(2)
counter external boundaries
integer, public :: k
simplicial order
integer, public :: surf_cnt
counter surface boundaries
integer, public, ALLOCATABLE :: work(:,:)
work array for merge sort
logical, public, ALLOCATABLE :: lwork(:)
work array to determine locality
Call graph
calc_bndry_cobndry: calls syncwrite_log:, num_elm:, syncwrite_log_time:, count_bndry_cobndry:, allocate_bndry_cobndry:, set_bndry_cobndry:, build_bndry_work_array:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls rootwrite_log:, mpi_barrier:, mpi_wtime:
count_bndry_cobndry: calls num_elm:, lcl_complex:, any_element_in_list:
allocate_bndry_cobndry: calls num_elm:, lcl_complex:
set_bndry_cobndry: calls num_elm:, lcl_complex:, elm2proc:
build_bndry_work_array: calls num_elm:, lcl_complex:
elm2proc: calls num_pelm_pp:
parallel_setup: calls calc_bndry_cobndry:
darcy_1f: calls parallel_setup:
darcy_crkp_2f: calls parallel_setup:
darcy: calls parallel_setup:
darcy_crkp_1f: calls parallel_setup:
darcy_crkp_2f~2: calls parallel_setup:
darcy_2f: calls parallel_setup: