calc_whitney_C2_BC – ParaGEMS
calc_whitney_C2_BC Subroutine
Pieter Boom
2019/08/23
47 statements
Source File
public subroutine calc_whitney_C2_BC()
Compute the Whitney interpolation of primal faces to primal volume barycentric centers
Arguments
None
Calls
Contents
Variables
f_vrts i indx j k vrts not_found grads
Variables
Type Visibility Attributes Name Initial
integer, public :: f_vrts(3)
face vertex indices
integer, public :: i
loop indices
integer, public :: indx
face index
integer, public :: j
loop indices
integer, public :: k
loop indices
integer, public :: vrts(4)
volume vertex indices
logical, public :: not_found
is boundary face index found
real(kind=iwp), public :: grads(4,3)
barycentric gradients
Call graph
calc_whitney_c2_bc: calls cross_product:, calc_barycentric_grad:, lcl_complex:, num_elm:
calc_barycentric_grad: calls matinv3:, matinv2: