calc_prml_unsgnd_vlm – ParaGEMS
calc_prml_unsgnd_vlm Subroutine
Pieter Boom
2019/08/23
23 statements
Source File
public subroutine calc_prml_unsgnd_vlm(k)
Compute unsigned volume of primal elements
Arguments
Type Intent Optional Attributes Name
integer :: k
loop counters
Calls
Called by
Contents
Variables
fac i j A pts
Variables
Type Visibility Attributes Name Initial
integer, public :: fac
factorial
integer, public :: i
loop counters
integer, public :: j
loop counters
real(kind=iwp), public, ALLOCATABLE :: A(:,:)
solution variable
real(kind=iwp), public, ALLOCATABLE :: pts(:)
bounding points
Call graph
calc_prml_unsgnd_vlm: calls lcl_complex:, num_elm:, determinant:
determinant: calls determinant:
initialise_geo: calls calc_prml_unsgnd_vlm: