clean_up – ParaGEMS
clean_up Subroutine
Pieter Boom
2019/08/21
5 statements
Source File
public subroutine clean_up()
Deallocate global structures/variables
Arguments
None
Called by
Contents
None
Call graph
darcy_1f: calls clean_up:
darcy_crkp_2f: calls clean_up:
darcy: calls clean_up:
darcy_crkp_1f: calls clean_up:
darcy_crkp_2f~2: calls clean_up:
darcy_2f: calls clean_up: