determinant – ParaGEMS
determinant Function
Pieter Boom
2019/08/29
26 statements
Source File
public recursive function determinant(A, n) result(accumulation)
Compute determinant
Arguments
Type Intent Optional Attributes Name
real(kind=iwp), intent(in) :: A(n,n)
integer, intent(in) :: n
Return Value real(kind=iwp)
Called by
Contents
Variables
i sgn B
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: sgn
real(kind=iwp), public :: B(n-1,n-1)
Call graph
determinant: calls determinant:
calc_unsgnd_vlm: calls determinant:
calc_prml_sgnd_vlm: calls determinant:
calc_prml_unsgnd_vlm: calls determinant:
calc_dual_vlm_i: calls calc_unsgnd_vlm:
initialise_geo: calls calc_prml_sgnd_vlm:, calc_prml_unsgnd_vlm:, calc_dual_vlm:
calc_dual_vlm: calls calc_dual_vlm_i: