elm2proc – ParaGEMS
elm2proc Function
Pieter Boom
2020/09/16
11 statements
Source File
public function elm2proc(id)
Convert partitioning element to process number (rank)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: id
Return Value integer
Calls
Called by
Contents
None
Call graph
elm2proc: calls num_pelm_pp:
read_bndry_cond: calls elm2proc:
read_prml_elms2: calls elm2proc:
read_crack_faces: calls elm2proc:
set_bndry_cobndry: calls elm2proc:
read_prml_elms: calls elm2proc:
read_glb_indx2: calls elm2proc:
read_glb_indx: calls elm2proc:
calc_bndry_cobndry: calls set_bndry_cobndry:
parallel_setup: calls read_prml_elms2:, calc_bndry_cobndry:, get_glb_indx:
get_glb_indx: calls read_glb_indx2:
darcy_1f: calls parallel_setup:
darcy_crkp_2f: calls parallel_setup:
darcy: calls parallel_setup:
darcy_crkp_1f: calls parallel_setup:
darcy_crkp_2f~2: calls parallel_setup:
darcy_2f: calls parallel_setup: