end_mpi – ParaGEMS
end_mpi Subroutine
Pieter Boom
2020/09/16
12 statements
Source File
public subroutine end_mpi()
End MPI execution environment & stop ParaGEMS
Arguments
None
Calls
Called by
Contents
Variables
str_out
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: str_out
STOP output string
Call graph
end_mpi: calls syncwrite_log:, mpi_finalize:, syncwrite_log_time:, close_log:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier:
darcy_1f: calls end_mpi:, start_mpi:, start_petsc:, read_input_darcy:, parallel_setup:
start_mpi: calls end_mpi:
start_petsc: calls end_mpi:
read_bndry_cond: calls end_mpi:
set_defaults_solver: calls end_mpi:
read_input_darcy: calls end_mpi:
int_merge_rows: calls end_mpi:
darcy_crkp_2f: calls end_mpi:, start_mpi:, start_petsc:, read_input_darcy:, parallel_setup:
darcy: calls end_mpi:, start_mpi:, start_petsc:, read_input_darcy:, parallel_setup:
darcy_crkp_1f: calls end_mpi:, start_mpi:, start_petsc:, read_input_darcy:, parallel_setup:
darcy_crkp_2f~2: calls end_mpi:, start_mpi:, start_petsc:, read_input_darcy:, parallel_setup:
read_glb_indx2: calls end_mpi:
t_start_mpi: calls end_mpi:
read_glb_indx: calls end_mpi:
darcy_2f: calls end_mpi:, start_mpi:, start_petsc:, read_input_darcy:, parallel_setup:
get_glb_indx: calls read_glb_indx2:
parallel_setup: calls get_glb_indx: