end_petsc – ParaGEMS
end_petsc Subroutine
Pieter Boom
2019/08/23
5 statements
Source File
public subroutine end_petsc()
Finalise PETSc library
Arguments
None
Calls
Called by
Contents
None
Call graph
end_petsc: calls petscfinalize:
darcy_1f: calls end_petsc:
darcy_crkp_2f: calls end_petsc:
darcy: calls end_petsc:
darcy_crkp_1f: calls end_petsc:
darcy_crkp_2f~2: calls end_petsc:
darcy_2f: calls end_petsc: