exchange_dual_vlm – ParaGEMS
exchange_dual_vlm Subroutine
Pieter Boom
2019/08/22
44 statements
Source File
public subroutine exchange_dual_vlm(k)
Exchange external dual volumes between adjacent processes
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: k
simplicial order
Calls
Called by
Contents
Variables
buffer_size cnt i junk kp req status rbuffer sbuffer
Variables
Type Visibility Attributes Name Initial
integer, public :: buffer_size
size of comm buffer
integer, public :: cnt
counter
integer, public :: i
loop index
integer, public :: junk
junk comm variable
integer, public :: kp
simplicial order plus one
integer, public, ALLOCATABLE :: req(:)
request variable for non-blocking comms
integer, public, ALLOCATABLE :: status(:,:)
size of MPI comm buffer
real(kind=iwp), public, ALLOCATABLE :: rbuffer(:)
receive buffer
real(kind=iwp), public, ALLOCATABLE :: sbuffer(:)
send buffer
Call graph
exchange_dual_vlm: calls lcl_complex:, mpi_waitall:, mpi_request_free:, mpi_barrier:, num_send:, adj_proc:, num_recv:
initialise_geo: calls exchange_dual_vlm: