exchange_bndry_cond – ParaGEMS
exchange_bndry_cond Subroutine
Pieter Boom
2019/08/23
44 statements
Source File
public subroutine exchange_bndry_cond(k)
exchange boundary conditions
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: k
simplicial order
Calls
Contents
Variables
buffer_size i j junk kp ptr ptrp rbuffer req sbuffer status
Variables
Type Visibility Attributes Name Initial
integer, public :: buffer_size
size of comm buffer
integer, public :: i
loop index
integer, public :: j
loop index
integer, public :: junk
junk comm variable
integer, public :: kp
simplicial order
integer, public :: ptr
pointer
integer, public :: ptrp
pointer
integer, public, ALLOCATABLE :: rbuffer(:)
receive buffer
integer, public, ALLOCATABLE :: req(:)
request variable for non-blocking comms
integer, public, ALLOCATABLE :: sbuffer(:)
send buffer
integer, public, ALLOCATABLE :: status(:,:)
size of MPI comm buffer
Call graph
exchange_bndry_cond: calls lcl_complex:, mpi_waitall:, mpi_request_free:, mpi_barrier:, num_send:, adj_proc:, num_recv: