exchange_prml_nodes – ParaGEMS
exchange_prml_nodes Subroutine
Pieter Boom
2020/09/16
41 statements
Source File
public subroutine exchange_prml_nodes()
Exchange nodal locations to adjacent process (ghost nodes)
Arguments
None
Calls
Called by
Contents
Variables
buffer_size j junk ptr req status rbuffer sbuffer
Variables
Type Visibility Attributes Name Initial
integer, public :: buffer_size
size of comm buffer
integer, public :: j
loop index
integer, public :: junk
junk comm variable
integer, public :: ptr
pointer
integer, public, ALLOCATABLE :: req(:)
request var (non-blking comm)
integer, public, ALLOCATABLE :: status(:,:)
size of MPI comm buffer
real(kind=iwp), public, ALLOCATABLE :: rbuffer(:)
send buffer
real(kind=iwp), public, ALLOCATABLE :: sbuffer(:)
send buffer
Call graph
exchange_prml_nodes: calls lcl_complex:, mpi_waitall:, mpi_request_free:, mpi_barrier:, num_send:, adj_proc:, num_recv:
parallel_setup: calls exchange_prml_nodes:
darcy_1f: calls parallel_setup:
darcy_crkp_2f: calls parallel_setup:
darcy: calls parallel_setup:
darcy_crkp_1f: calls parallel_setup:
darcy_crkp_2f~2: calls parallel_setup:
darcy_2f: calls parallel_setup: