exchange_dual_dir – ParaGEMS
exchange_dual_dir Subroutine
Pieter Boom
2019/08/22
44 statements
Source File
public subroutine exchange_dual_dir(k)
Exchange external dual edge directions between adjacent processes
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: k
simplicial order
Calls
Called by
Contents
Variables
buffer_size cnt i junk kp req status rbuffer sbuffer
Variables
Type Visibility Attributes Name Initial
integer, public :: buffer_size
size of comm buffer
integer, public :: cnt
counter
integer, public :: i
loop index
integer, public :: junk
junk comm variable
integer, public :: kp
simplicial order
integer, public, ALLOCATABLE :: req(:)
request variable for non-blocking comms
integer, public, ALLOCATABLE :: status(:,:)
size of MPI comm buffer
real(kind=iwp), public, ALLOCATABLE :: rbuffer(:)
receive buffer
real(kind=iwp), public, ALLOCATABLE :: sbuffer(:)
send buffer
Call graph
exchange_dual_dir: calls lcl_complex:, mpi_waitall:, mpi_request_free:, mpi_barrier:, num_send:, adj_proc:, num_recv:
calc_dual_dir: calls exchange_dual_dir:
initialise_geo: calls calc_dual_dir: