exchange_glb_indx – ParaGEMS
exchange_glb_indx Subroutine
Pieter Boom
2020/09/16
44 statements
Source File
public subroutine exchange_glb_indx(k)
Exchange global indices to adjacent process (ghost nodes)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: k
simplicial order
Calls
Called by
Contents
Variables
buffer_size i j junk kp ptr ptrp rbuffer req sbuffer status
Variables
Type Visibility Attributes Name Initial
integer, public :: buffer_size
size of comm buffer
integer, public :: i
loop index
integer, public :: j
loop index
integer, public :: junk
junk comm variable
integer, public :: kp
simplicial order
integer, public :: ptr
pointer
integer, public :: ptrp
pointer
integer, public, ALLOCATABLE :: rbuffer(:)
receive buffer
integer, public, ALLOCATABLE :: req(:)
request var (non-blking comm)
integer, public, ALLOCATABLE :: sbuffer(:)
send buffer
integer, public, ALLOCATABLE :: status(:,:)
size of MPI comm buffer
Call graph
exchange_glb_indx: calls lcl_complex:, mpi_waitall:, mpi_request_free:, mpi_barrier:, num_send:, adj_proc:, num_recv:
get_glb_indx: calls exchange_glb_indx:
parallel_setup: calls get_glb_indx:
darcy_1f: calls parallel_setup:
darcy_crkp_2f: calls parallel_setup:
darcy: calls parallel_setup:
darcy_crkp_1f: calls parallel_setup:
darcy_crkp_2f~2: calls parallel_setup:
darcy_2f: calls parallel_setup: