extract_sol_KSP2 – ParaGEMS
extract_sol_KSP2 Subroutine
Pieter Boom
2019/08/23
35 statements
Source File
public subroutine extract_sol_KSP2()
extract local solution values from distributed PETSc vector
scatter variable
Arguments
None
Calls
Called by
Contents
Variables
fname i from to lcl_sol sol1 sol2
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: i
loop index
is, public :: from
global and local vecor indices
is, public :: to
global and local vecor indices
vec, public :: lcl_sol
local solution vector
vec, public :: sol1
vec, public :: sol2
Call graph
extract_sol_ksp2: calls syncwrite_log_time:, vecscatterbegin:, vecscattercreate:, vecscatterend:, lcl_complex:, vecdestroy:, vecscatterdestroy:, num_elm:, isg:, isdestroy:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier:
darcy_crkp_2f: calls extract_sol_ksp2:
darcy_2f: calls extract_sol_ksp2: