extract_sol_KSP – ParaGEMS
extract_sol_KSP Subroutine
Pieter Boom
2019/08/23
31 statements
Source File
public subroutine extract_sol_KSP()
extract local solution values from distributed PETSc vector
scatter variable
Arguments
None
Calls
Called by
Contents
Variables
i from to lcl_sol
Variables
Type Visibility Attributes Name Initial
integer, public :: i
loop index
is, public :: from
global and local vecor indices
is, public :: to
global and local vecor indices
vec, public :: lcl_sol
local solution vector
Call graph
extract_sol_ksp: calls syncwrite_log_time:, vecscatterbegin:, vecscatterend:, lcl_complex:, vecdestroy:, vecscatterdestroy:, num_elm:, vecscattercreate:, glb_num_elm:, isdestroy:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier:
darcy_crkp_2f~2: calls extract_sol_ksp: