finalise_darcy – ParaGEMS
finalise_darcy Subroutine
Pieter Boom
2019/08/23
8 statements
Source File
public subroutine finalise_darcy()
clean up matrices and vectors for Darcy simulations
Arguments
None
Calls
Called by
Contents
None
Call graph
finalise_darcy: calls vecdestroy:, matdestroy:, kspdestroy:
darcy_1f: calls finalise_darcy:
darcy_crkp_2f: calls finalise_darcy:
darcy: calls finalise_darcy:
darcy_crkp_1f: calls finalise_darcy:
darcy_crkp_2f~2: calls finalise_darcy:
darcy_2f: calls finalise_darcy: