finalise_darcy2 – ParaGEMS
finalise_darcy2 Subroutine
Pieter Boom
2019/08/23
15 statements
Source File
public subroutine finalise_darcy2()
clean up matrices and vectors for Darcy simulations
Arguments
None
Calls
Contents
None
Call graph
finalise_darcy2: calls asub:, isg:, matdestroy:, kspdestroy:, vecdestroy: