get_RHS_darcy – ParaGEMS
get_RHS_darcy Subroutine
Pieter Boom
2019/08/23
75 statements
Source File
public subroutine get_RHS_darcy()
setup right hand side vector and boundary conditions for darcy simulations
Arguments
None
Calls
Called by
Contents
Variables
fname flx_indx i indx num_flx offset type_bc l_use_pref use_pref
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public, ALLOCATABLE :: flx_indx(:)
flx boundary condition indices
integer, public :: i
loop and temporary indicies
integer, public :: indx
loop and temporary indicies
integer, public :: num_flx
number of flux boundary faces
integer, public :: offset
vector offset for volumes (after faces)
integer, public :: type_bc
type of boundary condition
logical, public :: l_use_pref
use reference pressure (if no pressure bc used)
logical, public :: use_pref
use reference pressure (if no pressure bc used)
Call graph
get_rhs_darcy: calls syncwrite_log:, lcl_complex:, bc_press:, syncwrite_log_time:, vecassemblyend:, read_bndry_cond2:, num_elm:, mpi_wtime:, mpi_reduce:, vecassemblybegin:, glb_num_elm:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier:
read_bndry_cond2: calls lcl_complex:, num_elm:, glb_num_elm:, mpi_bcast:, root_open_file_read:, mpi_barrier:
root_open_file_read: calls mpi_bcast:
darcy_crkp_2f~2: calls get_rhs_darcy:
darcy_1f: calls get_rhs_darcy:
darcy: calls get_rhs_darcy:
darcy_crkp_1f: calls get_rhs_darcy: