get_connectivity – ParaGEMS
get_connectivity Subroutine
Pieter Boom
2020/09/16
120 statements
Source File
public subroutine get_connectivity()
Determine cross-process entity connections for all geometric orders
Arguments
None
Calls
Called by
Contents
Variables
msg i j junk k km ptr ptr2 ptr3 rbuffer req sbuffer status
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: msg
integer, public :: i
loop indices
integer, public :: j
loop indices
integer, public :: junk
junk variable
integer, public :: k
simplicial order
integer, public :: km
simplicial order
integer, public :: ptr
pointers
integer, public :: ptr2
pointers
integer, public :: ptr3
pointers
integer, public, ALLOCATABLE :: rbuffer(:)
boundary index
integer, public, ALLOCATABLE :: req(:)
request var (non-blking comms)
integer, public, ALLOCATABLE :: sbuffer(:)
boundary index
integer, public, ALLOCATABLE :: status(:,:)
status var (non-blking comms)
Call graph
get_connectivity: calls rootwrite_log:, lcl_complex:, adj_proc:, mpi_waitall:, mpi_request_free:, mpi_barrier:, num_send:, num_elm:, index_in_list:, num_recv:
parallel_setup: calls get_connectivity:
darcy_1f: calls parallel_setup:
darcy_crkp_2f: calls parallel_setup:
darcy: calls parallel_setup:
darcy_crkp_1f: calls parallel_setup:
darcy_crkp_2f~2: calls parallel_setup:
darcy_2f: calls parallel_setup: