get_glb_indx – ParaGEMS
get_glb_indx Subroutine
Pieter Boom
2020/09/16
10 statements
Source File
public subroutine get_glb_indx()
Get global entity indices from file
Arguments
None
Calls
Called by
Contents
Variables
k
Variables
Type Visibility Attributes Name Initial
integer, public :: k
simplicial order
Call graph
get_glb_indx: calls read_glb_indx2:, lcl_complex:, num_elm:, exchange_glb_indx:
read_glb_indx2: calls lcl_complex:, num_elm:, end_mpi:, root_open_file_read:, indx_offset:, mpi_bcast:, mpi_barrier:, elm2proc:, glb_num_elm:
exchange_glb_indx: calls lcl_complex:, mpi_request_free:, mpi_barrier:, mpi_waitall:, adj_proc:, num_recv:, num_send:
end_mpi: calls syncwrite_log:, mpi_finalize:, syncwrite_log_time:, close_log:
root_open_file_read: calls mpi_bcast:
elm2proc: calls num_pelm_pp:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_barrier:, mpi_wtime:, rootwrite_log:
parallel_setup: calls get_glb_indx:
darcy_1f: calls parallel_setup:
darcy_crkp_2f: calls parallel_setup:
darcy: calls parallel_setup:
darcy_crkp_1f: calls parallel_setup:
darcy_crkp_2f~2: calls parallel_setup:
darcy_2f: calls parallel_setup: