get_RHS_darcy2 – ParaGEMS
get_RHS_darcy2 Subroutine
Pieter Boom
2019/08/23
94 statements
Source File
public subroutine get_RHS_darcy2()
setup right hand side vector and boundary conditions for darcy simulations
Arguments
None
Calls
Called by
Contents
Variables
fname flx_indx i indx m n num_flx offset type_bc l_use_pref use_pref flx b1 b2 sol1 sol2 wrk
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public, ALLOCATABLE :: flx_indx(:)
flx boundary condition indices
integer, public :: i
loop and temporary indicies
integer, public :: indx
loop and temporary indicies
integer, public :: m
integer, public :: n
integer, public :: num_flx
number of flux boundary faces
integer, public :: offset
vector offset for volumes (after faces)
integer, public :: type_bc
type of boundary condition
logical, public :: l_use_pref
use reference pressure (if no pressure bc used)
logical, public :: use_pref
use reference pressure (if no pressure bc used)
real(kind=iwp), public :: flx
vec, public :: b1
vec, public :: b2
vec, public :: sol1
vec, public :: sol2
vec, public :: wrk
Call graph
get_rhs_darcy2: calls syncwrite_log:, lcl_complex:, matgetownershiprange:, bc_press:, syncwrite_log_time:, vecsetfromoptions:, vecassemblyend:, vecduplicate:, vecdestroy:, glb_num_elm:, num_elm:, asub:, mpi_wtime:, isg:, vecassemblybegin:, read_bndry_cond2:, matcreatenest:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier:
read_bndry_cond2: calls lcl_complex:, glb_num_elm:, num_elm:, mpi_bcast:, root_open_file_read:, mpi_barrier:
root_open_file_read: calls mpi_bcast:
darcy_crkp_2f: calls get_rhs_darcy2:
darcy_2f: calls get_rhs_darcy2: