get_LHS_darcy – ParaGEMS
get_LHS_darcy Subroutine
Pieter Boom
2019/08/23
21 statements
Source File
public subroutine get_LHS_darcy()
setup left hand side matrix for darcy simulations
Arguments
None
Calls
Called by
Contents
Variables
i j offset
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
integer, public :: offset
Call graph
get_lhs_darcy: calls syncwrite_log:, syncwrite_log_time:, lcl_complex:, matassemblybegin:, matsetoption:, num_elm:, mpi_wtime:, matassemblyend:, glb_num_elm:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier:
darcy_crkp_2f~2: calls get_lhs_darcy:
darcy_1f: calls get_lhs_darcy:
darcy: calls get_lhs_darcy:
darcy_crkp_1f: calls get_lhs_darcy: