get_LHS_darcy2 – ParaGEMS
get_LHS_darcy2 Subroutine
Pieter Boom
2019/08/23
53 statements
Source File
public subroutine get_LHS_darcy2()
setup left hand side matrix for darcy simulations
Arguments
None
Calls
Called by
Contents
Variables
i j m offset rnd
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: j
integer, public :: m
number of rows/columns in global solution variables
integer, public :: offset
real(kind=iwp), public :: rnd
Call graph
get_lhs_darcy2: calls syncwrite_log:, syncwrite_log_time:, asub:, lcl_complex:, glb_num_elm:, matsetoption:, matcreatenest:, num_elm:, mpi_wtime:, matnestgetiss:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier:
darcy_crkp_2f: calls get_lhs_darcy2:
darcy_2f: calls get_lhs_darcy2: