identify_crack4 – ParaGEMS
identify_crack4 Subroutine
Pieter Boom
2019/08/23
36 statements
Source File
public subroutine identify_crack4(iter, exit_cond)
identify faces to crack based on threshold value
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iter
logical, intent(out) :: exit_cond
Calls
Called by
Contents
Variables
flx_indx i j num_flx type_bc lcl_exit_cond
Variables
Type Visibility Attributes Name Initial
integer, public, ALLOCATABLE :: flx_indx(:)
flx boundary condition indices
integer, public :: i
loop and temporary indicies
integer, public :: j
loop and temporary indicies
integer, public :: num_flx
number of flux boundary faces
integer, public :: type_bc
type of boundary condition
logical, public :: lcl_exit_cond = .FALSE.
Call graph
identify_crack4: calls syncwrite_log:, vecassemblyend:, syncwrite_log_time:, asub:, lcl_complex:, mpi_allreduce:, num_elm:, mpi_wtime:, vecassemblybegin:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier:
darcy_crkp_2f: calls identify_crack4: