identify_crack2 – ParaGEMS
identify_crack2 Subroutine
Pieter Boom
2019/08/23
69 statements
Source File
public subroutine identify_crack2(exit_cond)
identify faces to crack based on threshold value
Arguments
Type Intent Optional Attributes Name
logical, intent(out) :: exit_cond
Calls
Contents
Variables
msg flx_indx glb_num_flx i indx j lcl_num_flx num_flx type_bc lcl_exit_cond flx flxs tmp_crck_thrshld
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: msg
integer, public, ALLOCATABLE :: flx_indx(:)
flx boundary condition indices
integer, public :: glb_num_flx
number of flux boundary faces
integer, public :: i
loop and temporary indicies
integer, public :: indx
loop and temporary indicies
integer, public :: j
loop and temporary indicies
integer, public :: lcl_num_flx
number of flux boundary faces
integer, public :: num_flx
number of flux boundary faces
integer, public :: type_bc
type of boundary condition
logical, public :: lcl_exit_cond = .FALSE.
real(kind=iwp), public :: flx
flx boundary condition indices
real(kind=iwp), public, ALLOCATABLE :: flxs(:)
flx boundary condition indices
real(kind=iwp), public :: tmp_crck_thrshld
flx boundary condition indices
Call graph
identify_crack2: calls syncwrite_log:, lcl_complex:, syncwrite_log_time:, vecassemblyend:, mpi_allreduce:, num_elm:, mpi_wtime:, vecassemblybegin:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier: