identify_crack3 – ParaGEMS
identify_crack3 Subroutine
Pieter Boom
2019/08/23
56 statements
Source File
public subroutine identify_crack3(iter, exit_cond)
identify faces to crack based on max value
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iter
logical, intent(out) :: exit_cond
Calls
Called by
Contents
Variables
msg i junk max_indx status area flx glb_max_flx max_flx
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: msg
integer, public :: i
loop and temporary indicies
integer, public :: junk
loop and temporary indicies
integer, public :: max_indx(2)
loop and temporary indicies
integer, public :: status(MPI_STATUS_SIZE)
size of MPI comm buffer
real(kind=iwp), public :: area
real(kind=iwp), public :: flx
real(kind=iwp), public :: glb_max_flx(3)
real(kind=iwp), public :: max_flx(3)
Call graph
identify_crack3: calls syncwrite_log:, lcl_complex:, matzerorowscolumns:, syncwrite_log_time:, vecassemblyend:, num_elm:, mpi_wtime:, mpi_reduce:, vecassemblybegin:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier:
darcy_crkp_2f~2: calls identify_crack3: