identify_crack6 – ParaGEMS
identify_crack6 Subroutine
Pieter Boom
2020/12/09
54 statements
Source File
public subroutine identify_crack6(iter, exit_cond)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: iter
logical, intent(out) :: exit_cond
Calls
Called by
Contents
Variables
msg i indx j junk status search area rnd
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: msg
integer, public :: i
loop and temporary indicies
integer, public :: indx
loop and temporary indicies
integer, public :: j
loop and temporary indicies
integer, public :: junk
loop and temporary indicies
integer, public :: status(MPI_STATUS_SIZE)
size of MPI comm buffer
logical, public :: search
real(kind=iwp), public :: area
real(kind=iwp), public :: rnd
Call graph
identify_crack6: calls syncwrite_log:, lcl_complex:, vecsetvalues:, syncwrite_log_time:, mpi_bcast:, asub:, vecassemblyend:, mpi_allreduce:, num_elm:, mpi_wtime:, mpi_reduce:, vecassemblybegin:, glb_num_elm:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier:
darcy_crkp_2f: calls identify_crack6: