initialise_geo – ParaGEMS
initialise_geo Subroutine
Pieter Boom
2019/08/23
48 statements
Source File
public subroutine initialise_geo()
Initialise geometric quantities for the given mesh
Arguments
None
Calls
Contents
Variables
str i k absminV maxV minV
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: str
string for writing to log file
integer, public :: i
loop counters
integer, public :: k
loop counters
real(kind=iwp), public :: absminV
min/max volumes
real(kind=iwp), public :: maxV
min/max volumes
real(kind=iwp), public :: minV
min/max volumes
Call graph
initialise_geo: calls calc_hodge_star:, syncwrite_log:, rootwrite_log:, calc_prml_sgnd_vlm:, calc_dual_vlm:, get_lcl_node_indx:, num_elm:, lcl_complex:, syncwrite_log_time:, calc_prml_dir:, calc_circumcenters:, glb_num_elm:, exchange_dual_vlm:, mpi_wtime:, calc_dual_dir:, calc_prml_unsgnd_vlm:
calc_hodge_star: calls num_elm:, lcl_complex:
syncwrite_log: calls mpi_barrier:
calc_prml_sgnd_vlm: calls num_elm:, lcl_complex:, determinant:
calc_dual_vlm: calls num_elm:, lcl_complex:, calc_dual_vlm_i:, add_points_i:
get_lcl_node_indx: calls num_elm:, lcl_complex:
syncwrite_log_time: calls rootwrite_log:, mpi_wtime:, mpi_barrier:
calc_prml_dir: calls num_elm:, lcl_complex:
calc_circumcenters: calls num_elm:, lcl_complex:, dsysv:
exchange_dual_vlm: calls lcl_complex:, adj_proc:, mpi_waitall:, mpi_request_free:, num_send:, mpi_barrier:, num_recv:
calc_dual_dir: calls num_elm:, lcl_complex:, exchange_dual_dir:
calc_prml_unsgnd_vlm: calls num_elm:, lcl_complex:, determinant:
determinant: calls determinant:
calc_dual_vlm_i: calls lcl_complex:, calc_unsgnd_vlm:
add_points_i: calls lcl_complex:
exchange_dual_dir: calls lcl_complex:, adj_proc:, mpi_waitall:, mpi_request_free:, num_send:, mpi_barrier:, num_recv:
calc_unsgnd_vlm: calls determinant: