initialise_darcy2 – ParaGEMS
initialise_darcy2 Subroutine
Pieter Boom
2019/08/23
10 statements
Source File
public subroutine initialise_darcy2()
initialise matrices and vectors for Darcy simulations
Arguments
None
Calls
Called by
Contents
Variables
m offset
Variables
Type Visibility Attributes Name Initial
integer, public :: m
number of rows/columns in global solution variables
integer, public :: offset
loop index
Call graph
initialise_darcy2: calls mpi_wtime:, syncwrite_log:, lcl_complex:, num_elm:, syncwrite_log_time:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier:
darcy_crkp_2f: calls initialise_darcy2:
darcy_2f: calls initialise_darcy2: