initialise_darcy – ParaGEMS
initialise_darcy Subroutine
Pieter Boom
2019/08/23
45 statements
Source File
public subroutine initialise_darcy()
initialise matrices and vectors for Darcy simulations
Arguments
None
Calls
Called by
Contents
Variables
fname fib i id iib m offset o_nnz work
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: fib
loop index
integer, public :: i
loop index
integer, public :: id
index
integer, public :: iib
loop index
integer, public :: m
number of rows/columns in global solution variables
integer, public :: offset
loop index
real(kind=iwp), public, ALLOCATABLE :: o_nnz(:)
vec, public :: work
PETSc work array
Call graph
initialise_darcy: calls syncwrite_log:, matcreate:, syncwrite_log_time:, veccreatempi:, vecsetfromoptions:, lcl_complex:, vecduplicate:, vecdestroy:, vecassemblyend:, vecgetvalues:, matsetsizes:, vecgetownershiprange:, num_elm:, mpi_wtime:, matsetfromoptions:, vecassemblybegin:, glb_num_elm:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier:
darcy_crkp_2f~2: calls initialise_darcy:
darcy_1f: calls initialise_darcy:
darcy: calls initialise_darcy:
darcy_crkp_1f: calls initialise_darcy: