int_merge_rows – ParaGEMS
int_merge_rows Subroutine
Pieter Boom
2019/08/23
41 statements
Source File
public subroutine int_merge_rows(A, B, C, irow, frow)
Merge rows of an array in ascending order Assumption: rows are already sorted in ascending order
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: A(:,:)
integer, intent(in) :: B(:,:)
integer, intent(inout) :: C(:,:)
integer, intent(in) :: irow
integer, intent(in) :: frow
Calls
Contents
Variables
i ir j k is_le
Variables
Type Visibility Attributes Name Initial
integer, public :: i
integer, public :: ir
integer, public :: j
integer, public :: k
logical, public :: is_le
Call graph
int_merge_rows: calls end_mpi:
end_mpi: calls syncwrite_log:, mpi_finalize:, syncwrite_log_time:, close_log:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier: