open_log – ParaGEMS
open_log Subroutine
Pieter Boom
2020/09/16
40 statements
Source File
public subroutine open_log()
Open log file from root process and write ParaGEMS header
Arguments
None
Calls
Called by
Contents
Variables
fname i err fexists
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: i = 0
counter
logical, public :: err = .FALSE.
error variable
logical, public :: fexists
logical for file existence
Call graph
open_log: calls mpi_bcast:
start_mpi: calls open_log:
darcy_1f: calls start_mpi:
darcy_crkp_2f: calls start_mpi:
darcy: calls start_mpi:
darcy_crkp_1f: calls start_mpi:
darcy_crkp_2f~2: calls start_mpi:
darcy_2f: calls start_mpi: