parallel_setup – ParaGEMS
parallel_setup Subroutine
Pieter Boom
2020/09/16
34 statements
Source File
public subroutine parallel_setup()
Sets up partitioning, read mesh and nodal locations, and sets connectivity
Arguments
None
Calls
Called by
Contents
Variables
i tmp_time tmp_time_int
Variables
Type Visibility Attributes Name Initial
integer, public :: i
counter
real(kind=IWP), public :: tmp_time
temporary timing variable
real(kind=IWP), public :: tmp_time_int
temporary timing variable
Call graph
parallel_setup: calls syncwrite_log:, get_connectivity:, syncwrite_log_time:, calc_bndry_cobndry:, read_prml_elms2:, partition_dual:, read_nodes_prml:, exchange_prml_nodes:, get_glb_indx_dual_vlm:, get_glb_indx:
syncwrite_log: calls mpi_barrier:
get_connectivity: calls mpi_waitall:, mpi_barrier:, num_elm:, rootwrite_log:, lcl_complex:, adj_proc:, index_in_list:, mpi_request_free:, num_send:, num_recv:
syncwrite_log_time: calls mpi_barrier:, rootwrite_log:, mpi_wtime:
calc_bndry_cobndry: calls syncwrite_log:, syncwrite_log_time:, count_bndry_cobndry:, num_elm:, allocate_bndry_cobndry:, build_bndry_work_array:, set_bndry_cobndry:
read_prml_elms2: calls mpi_barrier:, num_elm:, root_open_file_read:, elm2proc:, mpi_bcast:, lcl_complex:, num_pelm_pp:, glb_num_elm:, indx_offset:
partition_dual: calls num_elm:, mpi_bcast:, lcl_complex:, num_pelm_pp:, glb_num_elm:, indx_offset:
read_nodes_prml: calls mpi_recv:, num_elm:, root_open_file_read:, mpi_send:, mpi_bcast:, idnint:, lcl_complex:, num_pelm_pp:, glb_num_elm:, indx_offset:
exchange_prml_nodes: calls mpi_waitall:, mpi_barrier:, lcl_complex:, adj_proc:, mpi_request_free:, num_send:, num_recv:
get_glb_indx_dual_vlm: calls num_elm:, lcl_complex:
get_glb_indx: calls num_elm:, read_glb_indx2:, lcl_complex:, exchange_glb_indx:
count_bndry_cobndry: calls num_elm:, lcl_complex:, any_element_in_list:
read_glb_indx2: calls mpi_barrier:, num_elm:, root_open_file_read:, elm2proc:, mpi_bcast:, lcl_complex:, glb_num_elm:, indx_offset:, end_mpi:
root_open_file_read: calls mpi_bcast:
elm2proc: calls num_pelm_pp:
allocate_bndry_cobndry: calls num_elm:, lcl_complex:
build_bndry_work_array: calls num_elm:, lcl_complex:
exchange_glb_indx: calls mpi_waitall:, mpi_barrier:, lcl_complex:, adj_proc:, mpi_request_free:, num_send:, num_recv:
set_bndry_cobndry: calls num_elm:, elm2proc:, lcl_complex:
end_mpi: calls syncwrite_log:, syncwrite_log_time:, mpi_finalize:, close_log:
darcy_1f: calls parallel_setup:
darcy_crkp_2f: calls parallel_setup:
darcy: calls parallel_setup:
darcy_crkp_1f: calls parallel_setup:
darcy_crkp_2f~2: calls parallel_setup:
darcy_2f: calls parallel_setup: