partition_dual – ParaGEMS
partition_dual Subroutine
Pieter Boom
2020/09/16
84 statements
Source File
public subroutine partition_dual()
Partitions dual volumes across available processes Assumption: Mesh is a simplicial complex in TetGen format
Arguments
None
Calls
Called by
Contents
Variables
fname idx int_buffer junk k err
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: idx
index variable
integer, public :: int_buffer(6)
integer buffer for MPI comms
integer, public :: junk
junk IO variable
integer, public :: k
simplicial order
logical, public :: err = .FALSE.
error variable
Call graph
partition_dual: calls indx_offset:, mpi_bcast:, lcl_complex:, num_pelm_pp:, num_elm:, glb_num_elm:
parallel_setup: calls partition_dual:
darcy_1f: calls parallel_setup:
darcy_crkp_2f: calls parallel_setup:
darcy: calls parallel_setup:
darcy_crkp_1f: calls parallel_setup:
darcy_crkp_2f~2: calls parallel_setup:
darcy_2f: calls parallel_setup: