read_prml_elms2 – ParaGEMS
read_prml_elms2 Subroutine
Pieter Boom
2019/08/23
146 statements
Source File
public subroutine read_prml_elms2()
Read local node indices of highest order primal elements
Arguments
None
Calls
Called by
Contents
Variables
fname buffer_size dual_elm_in fib i ie iib in int_buffer j junk k l max_read_size num_dual_elm num_read_iters orient proc proc_old ptr read_size req resid_read_size status stride strt_indx err
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: buffer_size
size of MPI comm buffer
integer, public, ALLOCATABLE :: dual_elm_in(:)
node indices of dual element
integer, public :: fib
integer, public :: i
integer, public :: ie
loop indices (procs,elems)
integer, public :: iib
integer, public :: in
loop indices (procs,elems)
integer, public, ALLOCATABLE :: int_buffer(:)
integer buffer for MPI comms
integer, public :: j
integer, public :: junk
junk IO variable
integer, public :: k
simplicial order
integer, public :: l
integer, public :: max_read_size
integer, public :: num_dual_elm
number of local dual element
integer, public :: num_read_iters
integer, public :: orient
integer, public :: proc
processor rank (current, past)
integer, public :: proc_old
processor rank (current, past)
integer, public :: ptr
pointer
integer, public :: read_size
integer, public, ALLOCATABLE :: req(:)
request variable for non-blocking comms
integer, public :: resid_read_size
integer, public, ALLOCATABLE :: status(:)
size of MPI comm buffer
integer, public :: stride
integer, public :: strt_indx
logical, public :: err = .FALSE.
error variable
Call graph
read_prml_elms2: calls root_open_file_read:, indx_offset:, mpi_bcast:, lcl_complex:, num_pelm_pp:, mpi_barrier:, elm2proc:, num_elm:, glb_num_elm:
root_open_file_read: calls mpi_bcast:
elm2proc: calls num_pelm_pp:
parallel_setup: calls read_prml_elms2:
darcy_1f: calls parallel_setup:
darcy_crkp_2f: calls parallel_setup:
darcy: calls parallel_setup:
darcy_crkp_1f: calls parallel_setup:
darcy_crkp_2f~2: calls parallel_setup:
darcy_2f: calls parallel_setup: