read_glb_indx2 – ParaGEMS
read_glb_indx2 Subroutine
Pieter Boom
2019/08/23
100 statements
Source File
public subroutine read_glb_indx2(k)
Read local node indices of highest order primal elements
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: k
simplicial order
Calls
Called by
Contents
Variables
fname buffer_size fib i ie iib in int_buffer j junk l max_read_size n num_read_iters orient prml_elm proc proc_old ptr read_size req resid_read_size status stride strt_indx
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: buffer_size
size of MPI comm buffer
integer, public :: fib
integer, public :: i
loop indices (procs,elems)
integer, public :: ie
loop indices (procs,elems)
integer, public :: iib
integer, public :: in
loop indices (procs,elems)
integer, public, ALLOCATABLE :: int_buffer(:)
integer buffer for MPI comms
integer, public :: j
loop indices (procs,elems)
integer, public :: junk
junk IO variable
integer, public :: l
integer, public :: max_read_size
integer, public :: n
integer, public :: num_read_iters
integer, public :: orient
integer, public, ALLOCATABLE :: prml_elm(:,:)
primal element list
integer, public :: proc
processor rank (current, past)
integer, public :: proc_old
processor rank (current, past)
integer, public :: ptr
pointer
integer, public :: read_size
integer, public, ALLOCATABLE :: req(:)
request variable for non-blocking comms
integer, public :: resid_read_size
integer, public, ALLOCATABLE :: status(:)
size of MPI comm buffer
integer, public :: stride
integer, public :: strt_indx
Call graph
read_glb_indx2: calls end_mpi:, root_open_file_read:, indx_offset:, mpi_bcast:, lcl_complex:, mpi_barrier:, elm2proc:, num_elm:, glb_num_elm:
end_mpi: calls syncwrite_log:, mpi_finalize:, syncwrite_log_time:, close_log:
root_open_file_read: calls mpi_bcast:
elm2proc: calls num_pelm_pp:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_barrier:, mpi_wtime:, rootwrite_log:
get_glb_indx: calls read_glb_indx2:
parallel_setup: calls get_glb_indx:
darcy_1f: calls parallel_setup:
darcy_crkp_2f: calls parallel_setup:
darcy: calls parallel_setup:
darcy_crkp_1f: calls parallel_setup:
darcy_crkp_2f~2: calls parallel_setup:
darcy_2f: calls parallel_setup: