read_crack_faces – ParaGEMS
read_crack_faces Subroutine
Pieter Boom
2019/08/23
82 statements
Source File
public subroutine read_crack_faces()
read crack faces from file
Arguments
None
Calls
Contents
Variables
fname buffer_size glb_num_cracks i ie in int_buffer j junk prml_elm proc proc_old ptr req status
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: buffer_size
size of MPI comm buffer
integer, public :: glb_num_cracks
global number of cracks
integer, public :: i
loop indices (procs,elems)
integer, public :: ie
loop indices (procs,elems)
integer, public :: in
loop indices (procs,elems)
integer, public, ALLOCATABLE :: int_buffer(:,:)
integer buffer for MPI comms
integer, public :: j
loop indices (procs,elems)
integer, public :: junk
junk IO variable
integer, public, ALLOCATABLE :: prml_elm(:,:)
primal element list
integer, public :: proc
processor rank (current, past)
integer, public :: proc_old
processor rank (current, past)
integer, public :: ptr
pointer
integer, public, ALLOCATABLE :: req(:)
request variable for non-blocking comms
integer, public, ALLOCATABLE :: status(:)
size of MPI comm buffer
Call graph
read_crack_faces: calls lcl_complex:, root_open_file_read:, indx_offset:, mpi_bcast:, mpi_request_free:, mpi_barrier:, mpi_recv:, elm2proc:, num_elm:
root_open_file_read: calls mpi_bcast:
elm2proc: calls num_pelm_pp: