read_bndry_cond – ParaGEMS
read_bndry_cond Subroutine
Pieter Boom
2019/08/23
89 statements
Source File
public subroutine read_bndry_cond()
Read boundary conditions from file
Arguments
None
Calls
Contents
Variables
fname buffer_size i ie in int_buffer j junk node_indices prml_elm proc proc_old ptr req status
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: buffer_size
size of MPI comm buffer
integer, public :: i
loop indices (procs,elems)
integer, public :: ie
loop indices (procs,elems)
integer, public :: in
loop indices (procs,elems)
integer, public, ALLOCATABLE :: int_buffer(:,:)
integer buffer for MPI comms
integer, public :: j
loop indices (procs,elems)
integer, public :: junk
junk IO variable
integer, public, ALLOCATABLE :: node_indices(:)
junk IO variable for node indicies
integer, public, ALLOCATABLE :: prml_elm(:,:)
primal element list
integer, public :: proc
processor rank (current, past)
integer, public :: proc_old
processor rank (current, past)
integer, public :: ptr
pointer
integer, public, ALLOCATABLE :: req(:)
request variable for non-blocking comms
integer, public, ALLOCATABLE :: status(:)
size of MPI comm buffer
Call graph
read_bndry_cond: calls end_mpi:, lcl_complex:, root_open_file_read:, indx_offset:, mpi_request_free:, int_insertion_sort:, mpi_barrier:, elm2proc:, num_elm:, glb_num_elm:
end_mpi: calls syncwrite_log:, syncwrite_log_time:, mpi_finalize:, close_log:
root_open_file_read: calls mpi_bcast:
elm2proc: calls num_pelm_pp:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_barrier:, mpi_wtime:, rootwrite_log: