read_bndry_cond2 – ParaGEMS
read_bndry_cond2 Subroutine
Pieter Boom
2019/08/23
103 statements
Source File
public subroutine read_bndry_cond2()
Read boundary conditions from file
Arguments
None
Calls
Called by
Contents
Variables
fname buffer_size fib i ie iib in int_buffer j junk k l max_read_size node_indices num_read_iters orient prml_elm proc proc_old ptr read_size req resid_read_size status stride strt_indx
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: buffer_size
size of MPI comm buffer
integer, public :: fib
integer, public :: i
loop indices (procs,elems)
integer, public :: ie
loop indices (procs,elems)
integer, public :: iib
integer, public :: in
loop indices (procs,elems)
integer, public, ALLOCATABLE :: int_buffer(:)
integer buffer for MPI comms
integer, public :: j
loop indices (procs,elems)
integer, public :: junk
junk IO variable
integer, public :: k
integer, public :: l
integer, public :: max_read_size
integer, public, ALLOCATABLE :: node_indices(:)
junk IO variable for node indicies
integer, public :: num_read_iters
integer, public :: orient
integer, public, ALLOCATABLE :: prml_elm(:,:)
primal element list
integer, public :: proc
processor rank (current, past)
integer, public :: proc_old
processor rank (current, past)
integer, public :: ptr
pointer
integer, public :: read_size
integer, public, ALLOCATABLE :: req(:)
request variable for non-blocking comms
integer, public :: resid_read_size
integer, public, ALLOCATABLE :: status(:)
size of MPI comm buffer
integer, public :: stride
integer, public :: strt_indx
Call graph
read_bndry_cond2: calls root_open_file_read:, mpi_bcast:, lcl_complex:, mpi_barrier:, num_elm:, glb_num_elm:
root_open_file_read: calls mpi_bcast:
get_rhs_darcy: calls read_bndry_cond2:
get_rhs_darcy2: calls read_bndry_cond2:
darcy_1f: calls get_rhs_darcy:
darcy_2f: calls get_rhs_darcy2:
darcy: calls get_rhs_darcy:
darcy_crkp_1f: calls get_rhs_darcy:
darcy_crkp_2f~2: calls get_rhs_darcy:
darcy_crkp_2f: calls get_rhs_darcy2: