read_input_darcy – ParaGEMS
read_input_darcy Subroutine
Pieter Boom
2020/09/16
26 statements
Source File
public subroutine read_input_darcy()
Read input filefor user defined parameters, and perform checks to ensure reasonable values are set
Arguments
None
Calls
Called by
Contents
Variables
msg buffer fname
Variables
Type Visibility Attributes Name Initial
character(len=SLEN), public :: msg
error msg string
character(len=slen), public :: buffer
buffer for command line arguments
character(len=slen), public :: fname
file name
Call graph
read_input_darcy: calls end_mpi:, syncwrite_log:, rootwrite_log:, check_param_darcy:
end_mpi: calls syncwrite_log:, mpi_finalize:, syncwrite_log_time:, close_log:
syncwrite_log: calls mpi_barrier:
check_param_darcy: calls rootwrite_log:
syncwrite_log_time: calls rootwrite_log:, mpi_barrier:, mpi_wtime:
darcy_1f: calls read_input_darcy:
darcy_crkp_2f: calls read_input_darcy:
darcy: calls read_input_darcy:
darcy_crkp_1f: calls read_input_darcy:
darcy_crkp_2f~2: calls read_input_darcy:
darcy_2f: calls read_input_darcy: