read_prml_elms – ParaGEMS
read_prml_elms Subroutine
Pieter Boom
2019/08/23
88 statements
Source File
public subroutine read_prml_elms()
Read local node indices of highest order primal elements
Arguments
None
Calls
Contents
Variables
fname buffer_size dual_elm_in ie in int_buffer junk k num_dual_elm prml_elm proc proc_old ptr req status err
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: buffer_size
size of MPI comm buffer
integer, public, ALLOCATABLE :: dual_elm_in(:)
node indices of dual element
integer, public :: ie
loop indices (procs,elems)
integer, public :: in
loop indices (procs,elems)
integer, public, ALLOCATABLE :: int_buffer(:,:)
integer buffer for MPI comms
integer, public :: junk
junk IO variable
integer, public :: k
simplicial order
integer, public :: num_dual_elm
number of local dual element
integer, public, ALLOCATABLE :: prml_elm(:,:)
primal element list
integer, public :: proc
processor rank (current, past)
integer, public :: proc_old
processor rank (current, past)
integer, public :: ptr
pointer
integer, public, ALLOCATABLE :: req(:)
request variable for non-blocking comms
integer, public, ALLOCATABLE :: status(:)
size of MPI comm buffer
logical, public :: err = .FALSE.
error variable
Call graph
read_prml_elms: calls lcl_complex:, root_open_file_read:, indx_offset:, mpi_bcast:, mpi_request_free:, mpi_barrier:, elm2proc:, num_elm:, glb_num_elm:
root_open_file_read: calls mpi_bcast:
elm2proc: calls num_pelm_pp: