read_nodes_prml – ParaGEMS
read_nodes_prml Subroutine
Pieter Boom
2019/08/23
97 statements
Source File
public subroutine read_nodes_prml()
Root process reads the location of primal nodes
Arguments
None
Calls
Called by
Contents
Variables
fname buffer_size fib ie iib ip junk k ptr ptrp status err real_buffer
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: buffer_size
size of MPI comm buffer
integer, public :: fib
initial/final index for MPI comm buffer
integer, public :: ie
loop indices (procs,elems)
integer, public :: iib
initial/final index for MPI comm buffer
integer, public :: ip
loop indices (procs,elems)
integer, public :: junk
junk IO variable
integer, public :: k
simplicial order
integer, public :: ptr
integer, public :: ptrp
integer, public, ALLOCATABLE :: status(:)
size of MPI comm buffer
logical, public :: err = .FALSE.
error variable
real(kind=iwp), public, ALLOCATABLE :: real_buffer(:)
buffer for MPI comms
Call graph
read_nodes_prml: calls mpi_recv:, root_open_file_read:, indx_offset:, mpi_bcast:, idnint:, lcl_complex:, num_pelm_pp:, num_elm:, mpi_send:, glb_num_elm:
root_open_file_read: calls mpi_bcast:
parallel_setup: calls read_nodes_prml:
darcy_1f: calls parallel_setup:
darcy_crkp_2f: calls parallel_setup:
darcy: calls parallel_setup:
darcy_crkp_1f: calls parallel_setup:
darcy_crkp_2f~2: calls parallel_setup:
darcy_2f: calls parallel_setup: