rootwrite_log – ParaGEMS
rootwrite_log Subroutine
Pieter Boom
2020/09/16
9 statements
Source File
public subroutine rootwrite_log(msg)
Write unsynchronised message from root process to log file
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: msg
message string
Called by
Contents
None
Call graph
initialise_geo: calls rootwrite_log:, syncwrite_log_time:
get_connectivity: calls rootwrite_log:
syncwrite_log_time: calls rootwrite_log:
darcy_1f: calls rootwrite_log:, read_input_darcy:, end_mpi:, parallel_setup:, get_rhs_darcy:, get_lhs_darcy:, initialise_darcy:, start_mpi:, start_petsc:
check_param_darcy: calls rootwrite_log:
darcy_crkp_2f: calls rootwrite_log:, read_input_darcy:, end_mpi:, parallel_setup:, identify_crack6:, initialise_darcy2:, identify_crack7:, identify_crack5:, identify_crack4:, get_lhs_darcy2:, extract_sol_ksp2:, get_rhs_darcy2:, start_mpi:, start_petsc:
read_input_darcy: calls rootwrite_log:, check_param_darcy:, end_mpi:
darcy: calls rootwrite_log:, read_input_darcy:, end_mpi:, parallel_setup:, get_rhs_darcy:, get_lhs_darcy:, initialise_darcy:, start_mpi:, start_petsc:
darcy_crkp_1f: calls rootwrite_log:, read_input_darcy:, end_mpi:, parallel_setup:, get_rhs_darcy:, get_lhs_darcy:, initialise_darcy:, start_mpi:, start_petsc:
darcy_crkp_2f~2: calls rootwrite_log:, read_input_darcy:, end_mpi:, extract_sol_ksp:, parallel_setup:, get_rhs_darcy:, get_lhs_darcy:, identify_crack:, initialise_darcy:, identify_crack3:, start_mpi:, start_petsc:
darcy_2f: calls rootwrite_log:, read_input_darcy:, end_mpi:, parallel_setup:, initialise_darcy2:, get_lhs_darcy2:, extract_sol_ksp2:, get_rhs_darcy2:, start_mpi:, start_petsc:
end_mpi: calls syncwrite_log_time:
extract_sol_ksp: calls syncwrite_log_time:
parallel_setup: calls get_connectivity:, syncwrite_log_time:, calc_bndry_cobndry:, get_glb_indx:
write_unsteady_d0s2: calls syncwrite_log_time:
identify_crack6: calls syncwrite_log_time:
get_rhs_darcy: calls syncwrite_log_time:
write_solution_d0s2: calls syncwrite_log_time:
get_lhs_darcy: calls syncwrite_log_time:
identify_crack: calls syncwrite_log_time:
initialise_darcy2: calls syncwrite_log_time:
identify_crack7: calls syncwrite_log_time:
calc_bndry_cobndry: calls syncwrite_log_time:
identify_crack5: calls syncwrite_log_time:
identify_crack4: calls syncwrite_log_time:
write_unsteady_d0s: calls syncwrite_log_time:
identify_crack2: calls syncwrite_log_time:
initialise_darcy: calls syncwrite_log_time:
get_lhs_darcy2: calls syncwrite_log_time:
extract_sol_ksp2: calls syncwrite_log_time:
identify_crack3: calls syncwrite_log_time:
get_rhs_darcy2: calls syncwrite_log_time:
start_mpi: calls end_mpi:
start_petsc: calls end_mpi:
read_bndry_cond: calls end_mpi:
set_defaults_solver: calls end_mpi:
int_merge_rows: calls end_mpi:
read_glb_indx2: calls end_mpi:
t_start_mpi: calls end_mpi:
read_glb_indx: calls end_mpi:
get_glb_indx: calls read_glb_indx2: