root_open_file_read – ParaGEMS
root_open_file_read Subroutine
Pieter Boom
2019/08/23
16 statements
Source File
public subroutine root_open_file_read(fname, unit)
Open given file on root process for reading
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: fname
file name
integer, intent(in) :: unit
file unit
Calls
Called by
Contents
Variables
err
Variables
Type Visibility Attributes Name Initial
logical, public :: err = .FALSE.
error variable
Call graph
root_open_file_read: calls mpi_bcast:
read_bndry_cond: calls root_open_file_read:
read_prml_elms2: calls root_open_file_read:
read_crack_faces: calls root_open_file_read:
read_nodes_prml: calls root_open_file_read:
write_unsteady_d0s: calls root_open_file_read:
write_solution_d0s: calls root_open_file_read:
read_prml_elms: calls root_open_file_read:
read_glb_indx2: calls root_open_file_read:
read_glb_indx: calls root_open_file_read:
read_bndry_cond2: calls root_open_file_read:
get_rhs_darcy: calls read_bndry_cond2:
parallel_setup: calls read_prml_elms2:, read_nodes_prml:, get_glb_indx:
get_glb_indx: calls read_glb_indx2:
get_rhs_darcy2: calls read_bndry_cond2:
darcy_1f: calls get_rhs_darcy:, parallel_setup:
darcy_crkp_2f: calls parallel_setup:, get_rhs_darcy2:
darcy: calls get_rhs_darcy:, parallel_setup:
darcy_crkp_1f: calls get_rhs_darcy:, parallel_setup:
darcy_crkp_2f~2: calls get_rhs_darcy:, parallel_setup:
darcy_2f: calls parallel_setup:, get_rhs_darcy2: