set_defaults_solver – ParaGEMS
set_defaults_solver Subroutine
Pieter Boom
2019/08/23
12 statements
Source File
public subroutine set_defaults_solver(solver)
Set default values for solver
Arguments
Type Intent Optional Attributes Name
character(len=*) :: solver
Calls
Contents
None
Call graph
set_defaults_solver: calls end_mpi:
end_mpi: calls syncwrite_log:, mpi_finalize:, syncwrite_log_time:, close_log:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier: