solve_KSP – ParaGEMS
solve_KSP Subroutine
Pieter Boom
2019/08/23
31 statements
Source File
public subroutine solve_KSP()
Solve linear system using PETSc KSP
Arguments
None
Calls
Called by
Contents
Variables
msg iters rnorm
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: msg
message sting for log file
integer, public :: iters
number of iterations
real(kind=iwp), public :: rnorm
final residual norm
Call graph
solve_ksp: calls syncwrite_log:, pcfactorsetmatorderingtype:, kspsetfromoptions:, kspsolve:, kspcreate:, petscviewerandformatcreate:, kspsettolerances:, kspsetup:, kspgetpc:, kspgetresidualnorm:, kspview:, kspmonitorset:, mpi_wtime:, pcsettype:, kspsettype:, kspgetiterationnumber:, kspsetoperators:
syncwrite_log: calls mpi_barrier:
darcy_crkp_2f~2: calls solve_ksp:
darcy_1f: calls solve_ksp:
darcy: calls solve_ksp:
darcy_crkp_1f: calls solve_ksp: