solve_KSP2 – ParaGEMS
solve_KSP2 Subroutine
Pieter Boom
2019/08/23
52 statements
Source File
public subroutine solve_KSP2()
Solve linear system using PETSc KSP
Arguments
None
Calls
Called by
Contents
Variables
fname msg iters m n rnorm
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
character(len=slen), public :: msg
message sting for log file
integer, public :: iters
number of iterations
integer, public :: m
number of iterations
integer, public :: n
number of iterations
real(kind=iwp), public :: rnorm
final residual norm
Call graph
solve_ksp2: calls kspsolve:, kspcreate:, kspsetup:, kspgetconvergedreason:, sub2pc_id:, sub2ksp_id:, subksp_id:, kspgetresidualnorm:, pcsettype:, kspmonitorset:, kspsetoperators:, subpc_id:, petscviewerandformatcreate:, kspsettolerances:, pcsetup:, mpi_wtime:, kspsetfromoptions:, kspsettype:, syncwrite_log:, pcfieldsplitsetschurfacttype:, pcfieldsplitgetsubksp:, kspview:, pcfieldsplitsetschurpre:, kspgetpc:, pcfieldsplitsettype:, isg:, kspgetiterationnumber:, kspdestroy:
syncwrite_log: calls mpi_barrier:
darcy_crkp_2f: calls solve_ksp2:
darcy_2f: calls solve_ksp2: