start_mpi – ParaGEMS
start_mpi Subroutine
Pieter Boom
2020/09/16
24 statements
Source File
public subroutine start_mpi()
Start MPI execution environment & get details
Arguments
None
Calls
Called by
Contents
None
Call graph
start_mpi: calls end_mpi:, mpi_comm_size:, syncwrite_log_mpidata:, open_log:, mpi_init:, mpi_barrier:, mpi_wtime:, mpi_comm_rank:
end_mpi: calls syncwrite_log:, mpi_finalize:, syncwrite_log_time:, close_log:
syncwrite_log_mpidata: calls mpi_barrier:
open_log: calls mpi_bcast:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_barrier:, mpi_wtime:, rootwrite_log:
darcy_1f: calls start_mpi:
darcy_crkp_2f: calls start_mpi:
darcy: calls start_mpi:
darcy_crkp_1f: calls start_mpi:
darcy_crkp_2f~2: calls start_mpi:
darcy_2f: calls start_mpi: