start_petsc – ParaGEMS
start_petsc Subroutine
Pieter Boom
2019/08/23
10 statements
Source File
public subroutine start_petsc()
Initialise PETSc library
Arguments
None
Calls
Called by
Contents
None
Call graph
start_petsc: calls petscinitialize:, syncwrite_log:, end_mpi:
syncwrite_log: calls mpi_barrier:
end_mpi: calls syncwrite_log:, close_log:, mpi_finalize:, syncwrite_log_time:
syncwrite_log_time: calls mpi_barrier:, mpi_wtime:, rootwrite_log:
darcy_1f: calls start_petsc:
darcy_crkp_2f: calls start_petsc:
darcy: calls start_petsc:
darcy_crkp_1f: calls start_petsc:
darcy_crkp_2f~2: calls start_petsc:
darcy_2f: calls start_petsc: