syncwrite_log – ParaGEMS
syncwrite_log Subroutine
Pieter Boom
2020/09/16
10 statements
Source File
public subroutine syncwrite_log(msg)
Write uynchronised message from root process to log file
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: msg
message string
Calls
Called by
Contents
None
Call graph
syncwrite_log: calls mpi_barrier:
end_mpi: calls syncwrite_log:
initialise_darcy: calls syncwrite_log:
darcy: calls syncwrite_log:, end_mpi:, initialise_darcy:, parallel_setup:, get_rhs_darcy:, solve_ksp:, read_input_darcy:, start_petsc:, get_lhs_darcy:, start_mpi:
darcy_crkp_2f~2: calls syncwrite_log:, end_mpi:, initialise_darcy:, identify_crack:, parallel_setup:, get_rhs_darcy:, solve_ksp:, read_input_darcy:, start_petsc:, get_lhs_darcy:, identify_crack3:, start_mpi:
identify_crack: calls syncwrite_log:
write_unsteady_d0s2: calls syncwrite_log:
darcy_1f: calls syncwrite_log:, end_mpi:, initialise_darcy:, parallel_setup:, get_rhs_darcy:, solve_ksp:, read_input_darcy:, start_petsc:, get_lhs_darcy:, start_mpi:
write_solution_d0s2: calls syncwrite_log:
initialise_darcy2: calls syncwrite_log:
get_rhs_darcy2: calls syncwrite_log:
calc_bndry_cobndry: calls syncwrite_log:
darcy_crkp_1f: calls syncwrite_log:, end_mpi:, initialise_darcy:, parallel_setup:, get_rhs_darcy:, solve_ksp:, read_input_darcy:, start_petsc:, get_lhs_darcy:, start_mpi:
solve_ksp2: calls syncwrite_log:
parallel_setup: calls syncwrite_log:, calc_bndry_cobndry:, get_glb_indx:
get_rhs_darcy: calls syncwrite_log:
get_lhs_darcy2: calls syncwrite_log:
solve_ksp: calls syncwrite_log:
read_input_darcy: calls syncwrite_log:, end_mpi:
darcy_crkp_2f: calls syncwrite_log:, end_mpi:, initialise_darcy2:, get_rhs_darcy2:, solve_ksp2:, parallel_setup:, get_lhs_darcy2:, read_input_darcy:, start_petsc:, identify_crack7:, identify_crack6:, identify_crack5:, identify_crack4:, start_mpi:
write_unsteady_d0s: calls syncwrite_log:
initialise_geo: calls syncwrite_log:
start_petsc: calls syncwrite_log:, end_mpi:
get_lhs_darcy: calls syncwrite_log:
identify_crack7: calls syncwrite_log:
identify_crack6: calls syncwrite_log:
identify_crack5: calls syncwrite_log:
identify_crack4: calls syncwrite_log:
identify_crack3: calls syncwrite_log:
identify_crack2: calls syncwrite_log:
darcy_2f: calls syncwrite_log:, end_mpi:, initialise_darcy2:, get_rhs_darcy2:, solve_ksp2:, parallel_setup:, get_lhs_darcy2:, read_input_darcy:, start_petsc:, start_mpi:
start_mpi: calls end_mpi:
read_bndry_cond: calls end_mpi:
set_defaults_solver: calls end_mpi:
int_merge_rows: calls end_mpi:
read_glb_indx2: calls end_mpi:
t_start_mpi: calls end_mpi:
read_glb_indx: calls end_mpi:
get_glb_indx: calls read_glb_indx2: