syncwrite_log_time – ParaGEMS
syncwrite_log_time Subroutine
Pieter Boom
2020/09/16
13 statements
Source File
public subroutine syncwrite_log_time()
Write a synchronised message to log file with timings
Arguments
None
Calls
Called by
Contents
Variables
log_msg time
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: log_msg
message string
real(kind=iwp), public :: time
time variable
Call graph
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier:
end_mpi: calls syncwrite_log_time:
extract_sol_ksp: calls syncwrite_log_time:
initialise_geo: calls syncwrite_log_time:
identify_crack: calls syncwrite_log_time:
write_unsteady_d0s2: calls syncwrite_log_time:
write_solution_d0s2: calls syncwrite_log_time:
initialise_darcy2: calls syncwrite_log_time:
get_rhs_darcy2: calls syncwrite_log_time:
calc_bndry_cobndry: calls syncwrite_log_time:
parallel_setup: calls syncwrite_log_time:, calc_bndry_cobndry:, get_glb_indx:
get_rhs_darcy: calls syncwrite_log_time:
get_lhs_darcy2: calls syncwrite_log_time:
write_unsteady_d0s: calls syncwrite_log_time:
initialise_darcy: calls syncwrite_log_time:
extract_sol_ksp2: calls syncwrite_log_time:
get_lhs_darcy: calls syncwrite_log_time:
identify_crack7: calls syncwrite_log_time:
identify_crack6: calls syncwrite_log_time:
identify_crack5: calls syncwrite_log_time:
identify_crack4: calls syncwrite_log_time:
identify_crack3: calls syncwrite_log_time:
identify_crack2: calls syncwrite_log_time:
darcy_1f: calls end_mpi:, parallel_setup:, get_rhs_darcy:, initialise_darcy:, get_lhs_darcy:, start_mpi:, start_petsc:, read_input_darcy:
start_mpi: calls end_mpi:
start_petsc: calls end_mpi:
read_bndry_cond: calls end_mpi:
set_defaults_solver: calls end_mpi:
read_input_darcy: calls end_mpi:
int_merge_rows: calls end_mpi:
darcy_crkp_2f: calls end_mpi:, initialise_darcy2:, get_rhs_darcy2:, parallel_setup:, get_lhs_darcy2:, extract_sol_ksp2:, identify_crack7:, identify_crack6:, identify_crack5:, identify_crack4:, start_mpi:, start_petsc:, read_input_darcy:
darcy: calls end_mpi:, parallel_setup:, get_rhs_darcy:, initialise_darcy:, get_lhs_darcy:, start_mpi:, start_petsc:, read_input_darcy:
darcy_crkp_1f: calls end_mpi:, parallel_setup:, get_rhs_darcy:, initialise_darcy:, get_lhs_darcy:, start_mpi:, start_petsc:, read_input_darcy:
darcy_crkp_2f~2: calls end_mpi:, extract_sol_ksp:, identify_crack:, parallel_setup:, get_rhs_darcy:, initialise_darcy:, get_lhs_darcy:, identify_crack3:, start_mpi:, start_petsc:, read_input_darcy:
read_glb_indx2: calls end_mpi:
t_start_mpi: calls end_mpi:
read_glb_indx: calls end_mpi:
darcy_2f: calls end_mpi:, initialise_darcy2:, get_rhs_darcy2:, parallel_setup:, get_lhs_darcy2:, extract_sol_ksp2:, start_mpi:, start_petsc:, read_input_darcy:
get_glb_indx: calls read_glb_indx2: