syncwrite_log_mpidata – ParaGEMS
syncwrite_log_mpidata Subroutine
Pieter Boom
2020/09/16
8 statements
Source File
public subroutine syncwrite_log_mpidata()
Write a synchronised message with number of mpi ranks to log file
Arguments
None
Calls
Called by
Contents
None
Call graph
syncwrite_log_mpidata: calls mpi_barrier:
start_mpi: calls syncwrite_log_mpidata:
darcy_1f: calls start_mpi:
darcy_crkp_2f: calls start_mpi:
darcy: calls start_mpi:
darcy_crkp_1f: calls start_mpi:
darcy_crkp_2f~2: calls start_mpi:
darcy_2f: calls start_mpi: