t_start_mpi – ParaGEMS
t_start_mpi Subroutine
19 statements
Source File
public subroutine t_start_mpi()
Arguments
None
Calls
Contents
None
Call graph
t_start_mpi: calls end_mpi:, mpi_comm_size:, mpi_init:, mpi_comm_rank:
end_mpi: calls syncwrite_log:, mpi_finalize:, syncwrite_log_time:, close_log:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_wtime:, rootwrite_log:, mpi_barrier: