write_prml_volumes_MATLAB – ParaGEMS
write_prml_volumes_MATLAB Subroutine
Pieter Boom
2019/08/23
30 statements
Source File
public subroutine write_prml_volumes_MATLAB()
write primal volumes to file in MATLAB format
Arguments
None
Calls
Contents
Variables
fname i id work wrk1 wrk2
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: i
loop and temporary indicies
integer, public :: id
loop and temporary indicies
vec, public :: work
PETSc work array
vec, public :: wrk1
sub arrays
vec, public :: wrk2
sub arrays
Call graph
write_prml_volumes_matlab: calls petscviewerpushformat:, vecassemblyend:, petscviewerdestroy:, vecdestroy:, vecduplicate:, petscviewerasciiopen:, vecview:, num_elm:, lcl_complex:, isg:, vecassemblybegin:, petscobjectsetname: