write_pressure_MATLAB – ParaGEMS
write_pressure_MATLAB Subroutine
Pieter Boom
2019/08/23
68 statements
Source File
public subroutine write_pressure_MATLAB(iter)
write scaled pressure solution to file in MATLAB format
Arguments
Type Intent Optional Attributes Name
integer, intent(in), optional :: iter
iteration for file name
Calls
Contents
Variables
fname i indx j prelen cnt dxyz nan sol_edge work wrk1 wrk2
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: i
loop index
integer, public :: indx
face index
integer, public :: j
loop index
integer, public :: prelen
string pointer
real(kind=iwp), public, ALLOCATABLE :: cnt(:)
counter
real(kind=iwp), public :: dxyz
extrapolation variable
real(kind=iwp), public :: nan
nan variable
real(kind=iwp), public, ALLOCATABLE :: sol_edge(:)
solution variable for MATLAB output
vec, public :: work
PETSc work array
vec, public :: wrk1
sub arrays
vec, public :: wrk2
sub arrays
Call graph
write_pressure_matlab: calls petscviewerpushformat:, vecassemblyend:, lcl_complex:, vecduplicate:, vecdestroy:, petscviewerdestroy:, petscviewerasciiopen:, num_elm:, petscobjectsetname:, isg:, vecassemblybegin:, vecview: