write_unsteady_D0S2 – ParaGEMS
write_unsteady_D0S2 Subroutine
Pieter Boom
2019/08/23
294 statements
Source File
public subroutine write_unsteady_D0S2(sclr_name, vctr_name, iter)
write vtk solution at dual 0-cells for evolving simulations
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: sclr_name
scalar variable name (label)
character(len=*), intent(in) :: vctr_name
vector variable name (label)
integer, intent(in) :: iter
integer iteration number
Calls
Contents
Variables
fname buffer_size comm_size extra_comms fib gindx i iib int_buffer istatus j junk junk_int_buffer k kmax max_comm_size num_comm_iters prelen ptr req resid_comm_size status strt_indx tmp_time tmp_time_int junk_real_buffer real_buffer
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: buffer_size
integer, public :: comm_size
integer, public :: extra_comms
integer, public :: fib
integer, public :: gindx
integer, public :: i
integer, public :: iib
integer, public, ALLOCATABLE :: int_buffer(:)
integer, public, ALLOCATABLE :: istatus(:,:)
size of MPI comm buffer
integer, public :: j
integer, public :: junk
integer, public, ALLOCATABLE :: junk_int_buffer(:)
integer, public :: k
integer, public :: kmax
integer, public :: max_comm_size
integer, public :: num_comm_iters
integer, public :: prelen
integer, public :: ptr
integer, public, ALLOCATABLE :: req(:)
request variable for non-blocking comms
integer, public :: resid_comm_size
integer, public, ALLOCATABLE :: status(:)
size of MPI comm buffer
integer, public :: strt_indx
real(kind=IWP), public :: tmp_time
temporary timing variable
real(kind=IWP), public :: tmp_time_int
temporary timing variable
real(kind=iwp), public, ALLOCATABLE :: junk_real_buffer(:)
real(kind=iwp), public, ALLOCATABLE :: real_buffer(:)
Call graph
write_unsteady_d0s2: calls syncwrite_log:, lcl_complex:, syncwrite_log_time:, mpi_recv:, num_pelm_pp:, mpi_barrier:, num_elm:, root_open_file_write:, mpi_wtime:, mpi_send:, mpi_reduce:, glb_num_elm:
syncwrite_log: calls mpi_barrier:
syncwrite_log_time: calls mpi_barrier:, mpi_wtime:, rootwrite_log:
root_open_file_write: calls mpi_bcast: