write_solution_D0S – ParaGEMS
write_solution_D0S Subroutine
Pieter Boom
2019/08/23
153 statements
Source File
public subroutine write_solution_D0S(sclr_name, vctr_name)
write vtk solution at dual 0-cells
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: sclr_name
scalar variable name (label)
character(len=*), intent(in) :: vctr_name
vector variable name (label)
Calls
Contents
Variables
fname buffer_size extra_comms fib i iib int_buffer istatus j junk junk_int_buffer kmax ptr req status junk_real_buffer real_buffer
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: buffer_size
integer, public :: extra_comms
integer, public :: fib
integer, public :: i
integer, public :: iib
integer, public, ALLOCATABLE :: int_buffer(:)
integer, public, ALLOCATABLE :: istatus(:,:)
size of MPI comm buffer
integer, public :: j
integer, public :: junk
integer, public, ALLOCATABLE :: junk_int_buffer(:)
integer, public :: kmax
integer, public :: ptr
integer, public, ALLOCATABLE :: req(:)
request variable for non-blocking comms
integer, public, ALLOCATABLE :: status(:)
size of MPI comm buffer
real(kind=iwp), public, ALLOCATABLE :: junk_real_buffer(:)
real(kind=iwp), public, ALLOCATABLE :: real_buffer(:)
Call graph
write_solution_d0s: calls lcl_complex:, root_open_file_read:, indx_offset:, num_elm:, mpi_recv:, num_pelm_pp:, mpi_barrier:, mpi_request_free:, mpi_waitall:, root_open_file_write:, mpi_isend:, glb_num_elm:
root_open_file_read: calls mpi_bcast:
root_open_file_write: calls mpi_bcast: