write_prml_volumes_MATLAB2 – ParaGEMS
write_prml_volumes_MATLAB2 Subroutine
Pieter Boom
2019/08/23
25 statements
Source File
public subroutine write_prml_volumes_MATLAB2()
write primary volumes to file in MATLAB format
Arguments
None
Calls
Contents
Variables
fname i id m work
Variables
Type Visibility Attributes Name Initial
character(len=slen), public :: fname
file name
integer, public :: i
loop and temporary indicies
integer, public :: id
loop and temporary indicies
integer, public :: m
number of rows in global solution variables
vec, public :: work
PETSc work array
Call graph
write_prml_volumes_matlab2: calls petscviewerpushformat:, veccreatempi:, vecassemblyend:, glb_num_elm:, petscviewerdestroy:, vecdestroy:, petscviewerasciiopen:, petscobjectsetname:, num_elm:, lcl_complex:, vecassemblybegin:, vecview: